### ISSUE TITLE
Increase code readability with line breaks

### ISSUE THREAD

**Issue by sen1** [benhamilton/intro-data-capstone-biodiversity#1]
https://github.com/benhamilton/intro-data-capstone-biodiversity/blob/a0f19eec950c333142a5091a992146a7a024e591/submission/Project-BenHamilton-Biodiversity.py#L138

Good job here. However, I would add some line breaks to increase code readability. Code styling is not something we followed very closely in this course. However, it is very important. 
```
protection_counts = species.groupby('conservation_status')\
    .scientific_name.nunique().reset_index()\
    .sort_values(by='scientific_name')
```

Read the PEP8 guide for the maximum length of a code line:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by benhamilton** [comment]
It appears that the export from the ipython notebook (jupyter) to .py it stripped the backslashes from the line ends. Something for me to keep in mind for the future. 
https://www.dropbox.com/s/tn4ixcwlwygz1zy/Screenshot%202018-04-11%2008.48.20.png?dl=1
ta, Ben.

**Comment by benhamilton** [comment]
Fixed
