### ISSUE TITLE
redundant if

### ISSUE THREAD

**Issue by sen1** [benhamilton/intro-data-capstone-biodiversity#3]
https://github.com/benhamilton/intro-data-capstone-biodiversity/blob/a0f19eec950c333142a5091a992146a7a024e591/submission/Project-BenHamilton-Biodiversity.py#L177-L180

This is same as `return x != "No Intervention"`. So the `if` statement is redundant.

**Comment by benhamilton** [comment]
Thanks, so this function could be re-written as:
<code>
def calc_is_protected(row):
    x = row['conservation_status']
    x != "No Intervention"
</code>

**Comment by sen1** [comment]
def calc_is_protected(row):
    x = row['conservation_status']
    return x != "No Intervention"

**Comment by benhamilton** [comment]
ah!
of course. the `return`.
Thank you, Ben.
