### ISSUE TITLE
Choose a column to count

### ISSUE THREAD

**Issue by sen1** [benhamilton/intro-data-capstone-biodiversity#4]
https://github.com/benhamilton/intro-data-capstone-biodiversity/blob/a0f19eec950c333142a5091a992146a7a024e591/submission/Project-BenHamilton-Biodiversity.py#L190

If you dont specify a column to count, it will count all the available coumns by default. Also dont forget the `reset_index`.
```
category_counts = species.groupby(['category', 'is_protected'])\
                         .scientific_name.nunique().reset_index()
```

**Comment by benhamilton** [comment]
fixed
