### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [benhamilton/intro-data-capstone-biodiversity#6]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was excellent and very readable. There are a couple points where your code could be accomplished a bit more efficiently, but everything worked the way it was supposed to.

Presentation: I think your graphs look excellent. `species_info.csv` does not make a title by itself. I would change it to something like `Data exploration`. The figures are not supposed to be in the appendix. You should use them on slides where you explaining the data. 

Your recommendation is good. I would have loved to see a little bit more explanation about the calculations you made to reach them (perhaps include p-values, etc). I totally understand the inclination to not want to include too much technical information, but adding a bit in for context can go a long way.

One super nitpicky suggestion for readability is to use a nice color theme for your presentation.

Excellent work overall.

**Comment by benhamilton** [comment]
Thank you for your feedback, Ben.
